import type { ManifestData } from "./manifest-generator";

export function generateAgentsMd(manifest: ManifestData): string {
  const lines: string[] = [];

  lines.push(`# ${manifest.project.name} — Permission & Security Manifest`);
  lines.push("");
  lines.push(`> Auto-generated by Manifest on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`);
  lines.push(`> This file describes the security model, permissions, and technical operations of this codebase.`);
  lines.push("");

  lines.push("## Overview");
  lines.push("");
  lines.push(`- **Screens/Components**: ${manifest.summary.totalScreens}`);
  lines.push(`- **User Interactions**: ${manifest.summary.totalInteractions}`);
  lines.push(`- **API Endpoints**: ${manifest.summary.totalEndpoints}`);
  lines.push(`- **Data Entities**: ${manifest.summary.totalEntities}`);
  lines.push(`- **Security Roles**: ${manifest.summary.totalRoles}`);
  lines.push(`- **Average Criticality**: ${manifest.summary.averageCriticality}/100`);
  lines.push(`- **Security Coverage**: ${manifest.summary.securityCoverage}% of endpoints have explicit security annotations`);
  lines.push("");

  if (manifest.roles.length > 0) {
    lines.push("## Roles & Permissions");
    lines.push("");
    for (const role of manifest.roles) {
      lines.push(`### ${role.name}`);
      lines.push("");
      lines.push(`- **Criticality Range**: ${role.criticalityRange[0]}–${role.criticalityRange[1]}`);
      lines.push(`- **Accessible Endpoints** (${role.endpoints.length}):`);
      for (const ep of role.endpoints) {
        lines.push(`  - \`${ep.method} ${ep.path}\` → ${ep.controller}`);
      }
      lines.push("");
    }
  }

  if (manifest.endpoints.length > 0) {
    lines.push("## API Endpoints");
    lines.push("");
    lines.push("| Method | Path | Controller | Operation | Criticality | Roles | Sensitive Data |");
    lines.push("|--------|------|------------|-----------|-------------|-------|----------------|");
    for (const ep of manifest.endpoints) {
      const roles = ep.requiredRoles.length > 0 ? ep.requiredRoles.join(", ") : "—";
      const sensitive = ep.sensitiveFieldsAccessed.length > 0 ? "⚠ Yes" : "No";
      const controller = ep.controller && ep.controllerMethod
        ? `${ep.controller}.${ep.controllerMethod}`
        : ep.controller || ep.controllerMethod || "—";
      lines.push(`| ${ep.method} | \`${ep.path}\` | ${controller} | ${ep.technicalOperation} | ${ep.criticalityScore} | ${roles} | ${sensitive} |`);
    }
    lines.push("");
  }

  if (manifest.entities.length > 0) {
    lines.push("## Data Entities");
    lines.push("");
    for (const entity of manifest.entities) {
      lines.push(`### ${entity.name}`);
      lines.push("");
      if (entity.operations.length > 0) {
        lines.push(`- **Operations**: ${entity.operations.join(", ")}`);
      }
      if (entity.sensitiveFields.length > 0) {
        lines.push(`- **Sensitive Fields**: ${entity.sensitiveFields.map(f => `\`${f}\``).join(", ")}`);
      }
      if (entity.fieldMetadata.length > 0) {
        lines.push(`- **Fields**:`);
        for (const field of entity.fieldMetadata) {
          const tags: string[] = [];
          if (field.isId) tags.push("PK");
          if (field.isSensitive) tags.push("SENSITIVE");
          if (field.validations && field.validations.length > 0) tags.push(field.validations.join(", "));
          const tagStr = tags.length > 0 ? ` [${tags.join(" | ")}]` : "";
          lines.push(`  - \`${field.name}\`: ${field.type}${tagStr}`);
        }
      }
      if (entity.accessedBy.length > 0) {
        lines.push(`- **Accessed By**:`);
        for (const ref of entity.accessedBy) {
          lines.push(`  - ${ref.controller}.${ref.method} → \`${ref.endpoint}\``);
        }
      }
      lines.push("");
    }
  }

  const securityGaps = manifest.securityMatrix.filter(e => e.roles.length === 0 && e.guards.length === 0);
  if (securityGaps.length > 0) {
    lines.push("## Security Gaps");
    lines.push("");
    lines.push("The following endpoints have **no explicit security annotations or route guards**:");
    lines.push("");
    for (const gap of securityGaps) {
      const sensitive = gap.sensitiveData ? " ⚠ (accesses sensitive data)" : "";
      lines.push(`- \`${gap.method} ${gap.endpoint}\` — Criticality: ${gap.criticalityScore}${sensitive}`);
    }
    lines.push("");
  }

  const highCritical = manifest.securityMatrix.filter(e => e.criticalityScore >= 70);
  if (highCritical.length > 0) {
    lines.push("## High-Criticality Operations");
    lines.push("");
    lines.push("Operations with criticality ≥ 70 that require careful review:");
    lines.push("");
    for (const op of highCritical.sort((a, b) => b.criticalityScore - a.criticalityScore)) {
      const roles = op.roles.length > 0 ? `Roles: ${op.roles.join(", ")}` : "No roles defined";
      lines.push(`- \`${op.method} ${op.endpoint}\` — **${op.criticalityScore}** — ${roles}`);
    }
    lines.push("");
  }

  if (manifest.screens.length > 0) {
    lines.push("## Screens & Interactions");
    lines.push("");
    for (const screen of manifest.screens) {
      const route = screen.route ? ` (\`${screen.route}\`)` : "";
      const guards = screen.routeGuards.length > 0 ? ` [Guards: ${screen.routeGuards.join(", ")}]` : "";
      lines.push(`### ${screen.name}${route}${guards}`);
      lines.push("");
      const grouped = groupBy(screen.interactions, i => i.technicalOperation);
      for (const [op, interactions] of Object.entries(grouped)) {
        lines.push(`**${op}** (${interactions.length}):`);
        for (const i of interactions) {
          const ep = i.endpoint ? ` → \`${i.httpMethod} ${i.endpoint}\`` : "";
          lines.push(`- ${i.name}${ep}`);
        }
        lines.push("");
      }
    }
  }

  lines.push("---");
  lines.push(`*Generated from MANIFEST.json v${manifest.version} by Manifest*`);

  return lines.join("\n");
}

function groupBy<T>(arr: T[], fn: (item: T) => string): Record<string, T[]> {
  const result: Record<string, T[]> = {};
  for (const item of arr) {
    const key = fn(item);
    if (!result[key]) result[key] = [];
    result[key].push(item);
  }
  return result;
}
